-- MySQL Script generated by MySQL Workbench
-- Fri Oct 18 03:01:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Tourism
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Tourism
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tourism` DEFAULT CHARACTER SET utf8 ;
USE `Tourism` ;

-- -----------------------------------------------------
-- Table `Tourism`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tourism`.`Employees` (
  `id_employee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_employee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tourism`.`Booking tours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tourism`.`Booking tours` (
  `id_booking_tour` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `kurort` VARCHAR(45) NOT NULL,
  `healing` VARCHAR(45) NOT NULL,
  `transport` VARCHAR(45) NOT NULL,
  `excursions` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_booking_tour`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tourism`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tourism`.`Customers` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tourism`.`Hotels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tourism`.`Hotels` (
  `id_hotel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_hotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tourism`.`Tour operators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tourism`.`Tour operators` (
  `id_tour_operator` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `manager` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `website` VARCHAR(45) NOT NULL,
  `id_hotel` INT NOT NULL,
  `id_employee` INT NOT NULL,
  `id_booking_tour` INT NOT NULL,
  `id_customer` INT NOT NULL,
  INDEX `Hotels_idx` (`id_hotel` ASC) VISIBLE,
  INDEX `Employee_idx` (`id_employee` ASC) VISIBLE,
  INDEX `Booking tours_idx` (`id_booking_tour` ASC) VISIBLE,
  INDEX `Customers_idx` (`id_customer` ASC) VISIBLE,
  PRIMARY KEY (`id_tour_operator`),
  CONSTRAINT `Hotels`
    FOREIGN KEY (`id_hotel`)
    REFERENCES `Tourism`.`Hotels` (`id_hotel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Employees`
    FOREIGN KEY (`id_employee`)
    REFERENCES `Tourism`.`Employees` (`id_employee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Booking tours`
    FOREIGN KEY (`id_booking_tour`)
    REFERENCES `Tourism`.`Booking tours` (`id_booking_tour`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Customers`
    FOREIGN KEY (`id_customer`)
    REFERENCES `Tourism`.`Customers` (`id_customer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
